[package]
name = "sd-desktop"
version = "0.1.1"
description = "The universal file manager."
authors = ["Spacedrive Technology Inc."]
default-run = "sd-desktop"
license = { workspace = true }
repository = { workspace = true }
edition = { workspace = true }

[dependencies]
tauri = { version = "1.5.2", features = [
  "dialog-all",
  "linux-protocol-headers",
  "macos-private-api",
  "os-all",
  "path-all",
  "protocol-all",
  "shell-all",
  "updater",
  "window-all",
] }

rspc = { workspace = true, features = ["tauri"] }
sd-core = { path = "../../../core", features = [
  "ffmpeg",
  "location-watcher",
  "heif",
] }
tokio = { workspace = true, features = ["sync"] }
window-shadows = "0.2.1"
tracing = { workspace = true }
serde = "1.0.188"
percent-encoding = "2.3.0"
http = "0.2.9"
opener = { version = "0.6.1", features = ["reveal"] }
specta = { workspace = true }
tauri-specta = { workspace = true, features = ["typescript"] }
uuid = { version = "1.4.1", features = ["serde"] }
futures = "0.3"
axum = { version = "0.6.20", features = ["headers", "query"] }
rand = "0.8.5"

prisma-client-rust = { workspace = true }
sd-prisma = { path = "../../../crates/prisma" }

[target.'cfg(target_os = "linux")'.dependencies]
sd-desktop-linux = { path = "../crates/linux" }
webkit2gtk = { version = "0.18.2", features = ["v2_2"] }

[target.'cfg(target_os = "macos")'.dependencies]
sd-desktop-macos = { path = "../crates/macos" }

[target.'cfg(target_os = "windows")'.dependencies]
sd-desktop-windows = { path = "../crates/windows" }
webview2-com = "0.19.1"

[build-dependencies]
tauri-build = "1.5.0"

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
